### ISSUE TITLE
Unable to build noao/onedspec/smw

### ISSUE THREAD

**Issue by olebole** [iraf/iraf-v216#31]
Another one... IRAF is so much fun.

When trying to build `noao/onedspec/smw`, the following error appears:
```
check out file `libsmw.a = noaolib/libsmw.a'
warning: library `libsmw.a' not found
Warning, mkpkg line 20: dependency file `<funits.h>' not found
Warning, mkpkg line 22: dependency file `funits.h' not found
Warning, mkpkg line 22: dependency file `<smw.h>' not found
Warning, mkpkg line 22: dependency file `<units.h>' not found
Warning, mkpkg line 23: dependency file `smw.h' not found
Warning, mkpkg line 24: dependency file `smw.h' not found
Warning, mkpkg line 25: dependency file `smw.h' not found
Warning, mkpkg line 26: dependency file `smw.h' not found
Warning, mkpkg line 27: dependency file `smw.h' not found
Warning, mkpkg line 28: dependency file `smw.h' not found
Warning, mkpkg line 29: dependency file `smw.h' not found
Warning, mkpkg line 30: dependency file `smw.h' not found
Warning, mkpkg line 31: dependency file `smw.h' not found
Warning, mkpkg line 32: dependency file `smw.h' not found
Warning, mkpkg line 33: dependency file `smw.h' not found
Warning, mkpkg line 34: dependency file `smw.h' not found
Warning, mkpkg line 35: dependency file `smw.h' not found
Warning, mkpkg line 36: dependency file `smw.h' not found
Warning, mkpkg line 37: dependency file `smw.h' not found
Warning, mkpkg line 38: dependency file `smw.h' not found
Warning, mkpkg line 39: dependency file `smw.h' not found
Warning, mkpkg line 40: dependency file `smw.h' not found
Warning, mkpkg line 42: dependency file `smw.h' not found
Warning, mkpkg line 43: dependency file `smw.h' not found
Warning, mkpkg line 44: dependency file `smw.h' not found
Warning, mkpkg line 45: dependency file `smw.h' not found
Warning, mkpkg line 46: dependency file `smw.h' not found
Warning, mkpkg line 47: dependency file `smw.h' not found
Warning, mkpkg line 48: dependency file `units.h' not found
xc -c -w -/g -/m64 -p noao funits.x shdr.x smwclose.x smwct.x smwctfree.x smwctran.x smwdaxis.x smwequispec.x smwesms.x smwgapid.x smwgwattrs.x smwmerge.x smwmultispec.x smwmw.x smwnd.x smwndes.x smwnewcopy.x smwoldms.x smwonedspec.x smwopen.x smwopenim.x smwsapid.x smwsaveim.x smwsaxes.x smwsctran.x smwsmw.x smwswattrs.x units.x
funits.x:
Error on line 5 of funits.x: cannot find include file
   fun_open:
[...]
   fun_changed:
HSI is compiled NOVOS
shdr.x:
Error on line 7 of shdr.x: cannot find include file
Error on line 8 of shdr.x: cannot find include file
Error on line 9 of shdr.x: cannot find include file
[...] (more similar errors)
ranlib noaolib/libsmw.a
ranlib: 'noaolib/libsmw.a': No such file
Updated 28 files in libsmw.a
Warning, mkpkg line 25: module `libsmw.a' not found or returned error
check file `libsmw.a' into `noaolib$'
$checkin: file `libsmw.a' not found
Warning, mkpkg line 26: error during checkin of libsmw.a
Warning, mkpkg line 30: module `smw@onedspec' not found or returned error
Warning, mkpkg line 9: module `noaolib' not found or returned error
```

**Comment by RobSteele49** [comment]
The way I solved this was to take all of the PRs from olebole and steelewool and I'm now building this .a in my branch oleboleUpdates in steelewool/iraf-v216. Unless @iraf has a fix I'd recommend just merging the relevant PRs.

**Comment by olebole** [comment]
Since I didn't encounter this during the last 14 days, I am closing. Should be reopened when it is discovered again after applying all patches.

**Comment by RobSteele49** [comment]
I have a copy of Ole's merge-all in my steelewool repository. I was not getting the files libasttools.a and libsmw.a created until I created the directories  noao/astutil/noaolib and noao/onedspec/noaolib. I'm just curious if these directories were necessary for Ole to build? If they are necessary what mechanism would be the 'recommended' way to create them. As a hack I created the files and have README in each of them in my olebole/merge-all branch. I would also be curious if iraf has these directories in his local area?

**Comment by iraf** [comment]
If you're seeing 'noaolib' in any of the paths it means your environment is
messed up somehow, i.e. the 'noaolib$' logical path used in the mkpkg files
isn't being resolved to something like '/iraf/iraf/noao/lib'.  There should
NOT be an 'noaolib' anywhere.

**Comment by steelewool** [comment]
Fixed my environment and that resolved the problem. Thanks.

On May 24, 2017, at 3:46 PM, NOAO IRAF Project <notifications@github.com> wrote:

If you're seeing 'noaolib' in any of the paths it means your environment is
messed up somehow, i.e. the 'noaolib$' logical path used in the mkpkg files
isn't being resolved to something like '/iraf/iraf/noao/lib'. There should
NOT be an 'noaolib' anywhere.

**Comment by olebole** [comment]
Would you provide a pull request for that?

**Comment by RobSteele49** [comment]
Using my branch which is tracking your (Ole's) mege-all branch after I did a clean build (./install; /make linux64; make sysgen)  the library files libsmw.a and libasttools.a were both built correctly and in the correct location. The noaolib problem effectively went away.
