### ISSUE TITLE
MacOSX (64bit): zsvjmp.s does not assemble

### ISSUE THREAD

**Issue by olebole** [iraf/iraf-v216#41]
Trying to [compile IRAF on Travis CI](https://travis-ci.org/olebole/iraf-v216/jobs/229664926) (see #36) under MacOS 64 bit fails because `zsvjmp.s` does not assemble:
```
++sh -x setarch.sh
++ls -d as
+'[' as = as ']'
+rm -rf as
+ln -s as.macintel as
[...]
for i in zsvjmp
+gcc -c -I/Users/travis/.iraf/ -O -DMACOSX -DMACINTEL -DMACH64 -Wall -Wunused -m64 -g -DNOVOS -Wall ../as/zsvjmp.s -o zsvjmp.o
../as/zsvjmp.s:61:2: error: unknown directive
 .abs _mem_, 0
 ^
```
See the build log [here](https://travis-ci.org/olebole/iraf-v216/jobs/229664926#L187-L190). I am wondering how the binary distribution was compiled, since this is obviously not connected to a preinstalled binary version of IRAF.

**Comment by iraf** [comment]
Not sure what file you're building, but it works for me and the zsvjmp.s
only has 46 lines:

munch> cd /iraf/iraf/unix/as.macintel
munch> *gcc -c -O -DMACOSX -DMACINTEL -DMACH64 -Wall -Wunused -m64 -g
-DNOVOS -Wall zsvjmp.s*
munch> uname -a
Darwin munch-2.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3
16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
munch> gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr
--with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

**Comment by olebole** [comment]
I follow the installation advise:
```
IRAFARCH=`./vendor/voclient/getarch`
mkdir build_tmp
./install -v --term xterm --bindir `pwd`/build_tmp/bin --cache `pwd`/build_tmp/cache --imdir `pwd`/build_tmp/imdir --root `pwd` < /dev/null || true
make ${IRAFARCH}
make sysgen
```
This is documented in the Travis CI script [here](https://github.com/olebole/iraf-v216/blob/d6b4e21e02b035baaabf456415634cbb97e7ac02/.travis.yml#L14-L18).
And when looking into the [GNU Assembler manual](https://sourceware.org/binutils/docs/as/), I don't find a `.abs` directive, which is in the mentioned code. [Here is](https://travis-ci.org/olebole/iraf-v216/jobs/229865246#L32-L37)
```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
before_script.1
```
It seems that you are using the Apple assembler, while I (resp. Travis) uses the Gnu one.

I have no idea why the line number is wrong; it comes out so of the build process. The file is [unchanged from the original one](https://github.com/olebole/iraf-v216/blob/9e454f1e3d73c3177daf58a39d70009a3e2cb898/unix/as.macintel/zsvjmp.s) when the code is checked out.

**Comment by iraf** [comment]
The .abs instruction should be commented out, apparently wasn't on the copy
I used in the first commit.  Fixed now.  The mem common address is now set
with a --defsym,mem_=0 flag set in xc.c

**Comment by olebole** [comment]
Why don't you push those changes to github?
For this change, will you do this or shall I write a pull request for it?

**Comment by iraf** [comment]
On Mon, May 8, 2017 at 1:36 AM, Ole Streicher <notifications@github.com>
wrote:

> Why don't you push those changes to github?
>
I did

**Comment by olebole** [comment]
I can confirm that this is fixed; see https://travis-ci.org/olebole/iraf-v216/jobs/229881119
