### ISSUE TITLE
Old references to /iraf/iraf in libc.h

### ISSUE THREAD

**Issue by steelewool** [iraf/iraf-v216#7]
These two references look like they old and should be replaced. Does anyone have any thoughts on how the .h files should actually be referenced?

steele@steele-VirtualBox:~/git/iraf-v216/unix/hlib/libc$ grep "iraf/iraf" *
libc.h:#include "/iraf/iraf/unix/bin/f2c.h"
libc.h:#include "/iraf/iraf/unix/hlib/libc/vosproto.h"

**Comment by steelewool** [comment]
Just to clarify based on some e-mails and posts (@zcsteele @iraf @joequant @olebole) this problem as I see was the fact that source files were referencing '/iraf/iraf' in include statements. I would think this is something that can't be fixed by the .install file or by some use of CFLAGS. Even relative references to the intended source file would be better. Let me know what people think of a good long term solution and I'll implement that in my cleanup-/iraf/iraf branch. So in summary I see this as a source code problem/error.

**Comment by RobSteele49** [comment]
I'm pretty sure, but maybe @iraf or @zcsteele or @joequant or @olebole) can confirm if the make system (./install make liinux64 make sysgen) at some point is modifying source files and changing '/iraf/iraf' to something else (/home/steele/git/iraf-v216) during the build process. If this is the case it seems that this should be documented.

**Comment by olebole** [comment]
IMO it is ugly to modify existing files. The usual way is to have templates like `libc.h.in` with some placeholder in it, and to generate the final files (`libc.h`) from there.
But for the moment, it is more important to get the package built as intended. From there we can think about improvements.

**Comment by olebole** [comment]
Moving part of the discussion from #25:

>Something like an "iraf.h.in" template file is indeed more modern but there is no PR to implement this nor is there any suggestion of how a full binary distribution where /iraf/iraf is the default path would be handled by the install script. 

As I wrote: I think this should be done later only. This is however one of the many points where I ask myself why IRAF on _any_ decision they had to make, they went the non-standard way which makes it problematic later.

**Comment by joequant** [comment]
I think that the approach that I took was to just have libc.h include
iraf.h and then change the compile files so that the directory of iraf.h
set up in the compile command.

**Comment by steelewool** [comment]
As we now have PRs that allow a build I'm going to close this issue.
